dist: xenial

addons:
  apt:
    packages:
    - make
    - emacs

script:
  - make all

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
